services:
  postgres:
    image: postgres:16
    container_name: cp_postgres
    environment:
      POSTGRES_USER: cp
      POSTGRES_PASSWORD: cp
      POSTGRES_DB: control_plane
    ports:
      - "5432:5432"
    volumes:
      - cp_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cp_rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # UI
    environment:
      RABBITMQ_DEFAULT_USER: cp
      RABBITMQ_DEFAULT_PASS: cp

  registry:
    image: registry:2
    container_name: cp_registry
    ports:
      - "5001:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
  
  nginx:
    image: nginx:alpine
    container_name: cp_nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - cp_net

  redis:
    image: redis:7-alpine
    container_name: cp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  minio:
    image: minio/minio:latest
    container_name: cp_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: cp_clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9009:9000"   # Native protocol (mapped to avoid conflict with MinIO)
    volumes:
      - clickhouse_data:/var/lib/clickhouse

networks:
# cp_net is a Docker bridge network whose sole purpose is to create a
# private, isolated communication channel between Nginx and the user's
# deployed app containers.
  cp_net:
    name: cp_net
    driver: bridge

volumes:
  cp_pgdata:
  redis_data:
  minio_data:
  clickhouse_data:
